on: push
name: 🚀 Deploy plugin on push
jobs:
  deploy_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Copy to staging directory for deployment
        run: |
          mkdir .deploy
          rsync -av --progress --delete . .deploy --exclude .git --exclude .deploy --exclude node_modules --exclude .gitignore --exclude .github

          rmdir .deploy/appp-preview/dist
          rmdir .deploy/appp-preview/src
        
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.USERNAME }}
            server: ${{ secrets.SERVER }}
            port: ${{ secrets.PORT }}
            local_path: './.deploy'
            remote_path: ${{ secrets.REMOTE_PATH }}
            sftp_only: true
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
