name: Deploy Files

on:
  push:
    branches:
      - main
  # Enables manually triggering of Workflow with file synchronization option..
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "full"

jobs:
  deploy-master:
    name: "main branch"
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          sync: "full"
          remote-protocol: "sftp"
          remote-host: ${{ secrets.SERVER }}
          remote-user: ${{ secrets.USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-path: ${{ secrets.REMOTE_PATH }}
