on: push
name: 🚀 Deploy website on push
jobs:
  deploy_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
        uses: actions/checkout@v2
        
        - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.USERNAME }}
            server: ${{ secrets.SERVER }}
            port: ${{ secrets.PORT }}
            local_path: './'
            remote_path: ${{ secrets.REMOTE_PATH }}
            sftp_only: true
            password: ${{ secrets.PASSWORD }}
